config/routes.rb
Rails.application.routes.draw do
  root 'champions#index'
  resources :champions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/champion.rb
class Champion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]

  # GET /champions
  # GET /champions.json
  def index
    @champions = Champion.all
  end

  # GET /champions/1
  # GET /champions/1.json
  def show
  end

  # GET /champions/new
  def new
    @champion = Champion.new
  end

  # GET /champions/1/edit
  def edit
  end

  # POST /champions
  # POST /champions.json
  def create
    @champion = Champion.new(champion_params)

    respond_to do |format|
      if @champion.save
        format.html { redirect_to @champion, notice: 'Champion was successfully created.' }
        format.json { render :show, status: :created, location: @champion }
      else
        format.html { render :new }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /champions/1
  # PATCH/PUT /champions/1.json
  def update
    respond_to do |format|
      if @champion.update(champion_params)
        format.html { redirect_to @champion, notice: 'Champion was successfully updated.' }
        format.json { render :show, status: :ok, location: @champion }
      else
        format.html { render :edit }
        format.json { render json: @champion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /champions/1
  # DELETE /champions/1.json
  def destroy
    @champion.destroy
    respond_to do |format|
      format.html { redirect_to champions_url, notice: 'Champion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_champion
      @champion = Champion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def champion_params
      params.require(:champion).permit(:name, :race, :faction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/views/champions/_form.html.erb
<%= form_with(model: champion, local: true) do |form| %>
  <% if champion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(champion.errors.count, "error") %> prohibited this champion from being saved:</h2>

      <ul>
      <% champion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :race %>
    <%= form.text_field :race %>
  </div>

  <div class="field">
    <%= form.label :faction %>
    <%= form.text_field :faction %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/champions/edit.html.erb
<h1>Editing Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Show', @champion %> |
<%= link_to 'Back', champions_path %>

app/views/champions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Champions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Race</th>
      <th>Faction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @champions.each do |champion| %>
      <tr>
        <td><%= champion.name %></td>
        <td><%= champion.race %></td>
        <td><%= champion.faction %></td>
        <td><%= link_to 'Show', champion %></td>
        <td><%= link_to 'Edit', edit_champion_path(champion) %></td>
        <td><%= link_to 'Destroy', champion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Champion', new_champion_path %>

app/views/champions/new.html.erb
<h1>New Champion</h1>

<%= render 'form', champion: @champion %>

<%= link_to 'Back', champions_path %>

app/views/champions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @champion.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @champion.race %>
</p>

<p>
  <strong>Faction:</strong>
  <%= @champion.faction %>
</p>

<%= link_to 'Edit', edit_champion_path(@champion) %> |
<%= link_to 'Back', champions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>